import { HierarchyData } from './hierarchy-data';

export let TheFederalHierarchy: HierarchyData = 
  { level: 0, id: '0000', name: 'Federal Hierarchy', shortname: '', children: [
	{ level: 1, id: '0938', name: 'ABRAHAM LINCOLN BICENTENNIAL COMMISSION' },
	{ level: 1, id: '9515', name: 'ADMINISTRATIVE CONFERENCE OF THE U. S.'},
	{ level: 1, id: '1027', name: 'ADMINISTRATIVE OFFICE OF THE U.S. COURTS'},
	{ level: 1, id: '0915', name: 'ADVISORY COMMISSION ON ELECTRONIC COMMERCE'},
	{ level: 1, id: '5500', name: 'ADVISORY COMMISSION ON INTERGOVERNMENTAL RELATIONS'},
	{ level: 1, id: '9530', name: 'ADVISORY COUNCIL ON HISTORIC PRESERVATION'},
	{ level: 1, id: '7200', name: 'AGENCY FOR INTERNATIONAL DEVELOPMENT'},
	{ level: 1, id: '1200', name: 'AGRICULTURE, DEPARTMENT OF'},
	{ level: 1, id: '7400', name: 'AMERICAN BATTLE MONUMENTS COMMISSION'},
	{ level: 1, id: '0977', name: 'ANTITRUST MODERNIZATION COMMISSION'},
	{ level: 1, id: '4602', name: 'APPALACHIAN REGIONAL COMMISSION'},
	{ level: 1, id: '0100', name: 'ARCHITECT OF THE CAPITOL'},
	{ level: 1, id: '9532', name: 'ARCHITECTURAL AND TRANSPORTATION BARRIERS COMPLIANCE BOARD'},
	{ level: 1, id: '84AF', name: 'ARMED FORCES RETIREMENT HOME'},
	{ level: 1, id: '1021', name: 'BANKRUPTCY COURTS'},
	{ level: 1, id: '9560', name: 'BARRY GOLDWATER SCHOLARSHIP AND EXCELLENCE IN EDUCATION FUND'},
	{ level: 1, id: '0910', name: 'BIOMEDICAL ETHICS BOARD'},
	{ level: 1, id: '9501', name: 'BOARD FOR INTERNATIONAL BROADCASTING'},
	{ level: 1, id: '0902', name: 'BOTANIC GARDEN'},
	{ level: 1, id: '9522', name: 'CENTENNIAL OF FLIGHT COMMISSION'},
	{ level: 1, id: '5600', name: 'CENTRAL INTELLIGENCE AGENCY'},
	{ level: 1, id: '9565', name: 'CHEMICAL SAFETY AND HAZARD INVESTIGATION BOARD'},
	{ level: 1, id: '7635', name: 'CHRISTOPHER COLUMBUS FELLOWSHIP FOUNDATION'},
	{ level: 1, id: '7608', name: 'CHRISTOPHER COLUMBUS QUINCENTENARY JUBILEE COMMISSION'},
	{ level: 1, id: '1300', name: 'COMMERCE, DEPARTMENT OF'},
	{ level: 1, id: '9567', name: 'COMMISSION FOR THE PRESERVATION OF AMERICA\'S HERITAGE ABROAD'},
	{ level: 1, id: '4853', name: 'COMMISSION FOR THE STUDY OF INTERNATIONAL MIGRATION AND COOP ECONOMIC DEVELOPMENT'},
	{ level: 1, id: '9537', name: 'COMMISSION OF FINE ARTS'},
	{ level: 1, id: '0911', name: 'COMMISSION ON AGRICULTURAL WORKERS'},
	{ level: 1, id: '9517', name: 'COMMISSION ON CIVIL RIGHTS'},
	{ level: 1, id: '4836', name: 'COMMISSION ON EXECUTIVE, LEGISLATIVE, AND JUDICIAL SALARIES'},
	{ level: 1, id: '0912', name: 'COMMISSION ON INTERSTATE CHILD SUPPORT'},
	{ level: 1, id: '9581', name: 'COMMISSION ON NATIONAL AND COMMUNITY SERVICE'},
	{ level: 1, id: '4827', name: 'COMMISSION ON OCEAN POLICY'},
	{ level: 1, id: '0901', name: 'COMMISSION ON SECURITY AND COOPERATION IN EUROPE'},
	{ level: 1, id: '7609', name: 'COMMISSION ON THE BICENTENNIAL OF THE U.S. CONSTITUTION'},
	{ level: 1, id: '0923', name: 'COMMISSION ON THE PEOPLES REPUBLIC OF CHINA'},
	{ level: 1, id: '0975', name: 'COMMISSION ON THE REVIEW OF THE OVERSEAS MILITARY FACILITY STRUCTURE OF THE U.S'},
	{ level: 1, id: '9518', name: 'COMMITTEE FOR PURCHASE FROM PEOPLE WHO ARE BLIND OR SEVERELY DISABLED'},
	{ level: 1, id: '9507', name: 'COMMODITY FUTURES TRADING COMMISSION'},
	{ level: 1, id: '9582', name: 'COMPETITIVENESS PAY COUNCIL'},
	{ level: 1, id: '0800', name: 'CONGRESSIONAL BUDGET OFFICE'},
	{ level: 1, id: '955F', name: 'CONSUMER FINANCIAL PROTECTION BUREAU'},
	{ level: 1, id: '6100', name: 'CONSUMER PRODUCT SAFETY COMMISSION'},
	{ level: 1, id: '0903', name: 'COPYRIGHT ROYALTY TRIBUNAL'},
	{ level: 1, id: '9577', name: 'CORPORATION FOR NATIONAL AND COMMUNITY SERVICE'},
	{ level: 1, id: '1025', name: 'COURT SECURITY'},
	{ level: 1, id: '9594', name: 'COURT SERVICES AND OFFENDER SUPERVISION AGENCY'},
	{ level: 1, id: '9516', name: 'DEFENSE NUCLEAR FACILITIES SAFETY BOARD'},
	{ level: 1, id: '4601', name: 'DELAWARE RIVER BASIN COMMISSION'},
	{ level: 1, id: '9547', name: 'DELTA REGIONAL AUTHORITY'},
	{ level: 1, id: '9572', name: 'DENALI COMMISSION'},
	{ level: 1, id: '9700', name: 'DEPT OF DEFENSE', shortname: 'DOD', children: [
		{ level: 2, id: '97AE', name: 'DEFENSE ADVANCED RESEARCH PROJECTS AGENCY', shortname: 'DARPA' },
		{ level: 2, id: '97AZ', name: 'DEFENSE COMMISSARY AGENCY', shortname: 'DECA'},
		{ level: 2, id: '97AR', name: 'DEFENSE CONTRACT AUDIT AGENCY', shortname: ''},
		{ level: 2, id: '9763', name: 'DEFENSE CONTRACT MANAGEMENT AGENCY', shortname: 'DCMA'},
		{ level: 2, id: '97BZ', name: 'DEFENSE FINANCE AND ACCOUNTING SERVICE', shortname: 'DFAS'},
		{ level: 2, id: '97DH', name: 'DEFENSE HEALTH AGENCY', shortname: 'DHA'},
		{ level: 2, id: '9748', name: 'DEFENSE HUMAN RESOURCES ACTIVITY', shortname: ''},
		{ level: 2, id: '97AK', name: 'DEFENSE INFORMATION SYSTEMS AGENCY ', shortname: 'DISA'},
		{ level: 2, id: '97DL', name: 'DEFENSE INTELLIGENCE AGENCY', shortname: 'DIA'},
		{ level: 2, id: '97AS', name: 'DEFENSE LOGISTICS AGENCY', shortname: 'DLA'},
		{ level: 2, id: '97F1', name: 'DEFENSE MEDIA ACTIVITY', shortname: 'DMA'},
		{ level: 2, id: '9771', name: 'DEFENSE MICROELECTRONICS ACTIVITY', shortname: 'DMEA'},
		{ level: 2, id: '9758', name: 'DEFENSE POW/MIA OFFICE', shortname: ''},
		{ level: 2, id: '97AT', name: 'DEFENSE SECURITY COOPERATION AGENCY', shortname: ''},
		{ level: 2, id: '97AV', name: 'DEFENSE SECURITY SERVICE', shortname: ''},
		{ level: 2, id: '9761', name: 'DEFENSE THREAT REDUCTION AGENCY', shortname: 'DTRA'},
		{ level: 2, id: '9700', name: 'DEPT OF DEFENSE', shortname: ''},
		{ level: 2, id: '97F2', name: 'DEPT OF DEFENSE EDUCATION ACTIVITY', shortname: 'DODEA'},
		{ level: 2, id: '5700', name: 'DEPT OF THE AIR FORCE', shortname: ''},
		{ level: 2, id: '2100', name: 'DEPT OF THE ARMY', shortname: '', children: [
			{level: 3, id: 'AMC', name: 'AMC', shortname: ''},
			{level: 3, id: 'ATEC', name: 'ATEC', shortname: '' },
			{level: 3, id: 'C-JTSCC', name: 'C-JTSCC', shortname: '' },
			{level: 3, id: 'INSCOM', name: 'INSCOM', shortname: '' },
			{level: 3, id: 'MEDCOM', name: 'MEDCOM', shortname: '' },
			{level: 3, id: 'NGB', name: 'NGB', shortname: '' },
			{level: 3, id: 'USAASC', name: 'US ARMY ACQUISITION SUPPORT CENTER', shortname: '' },
			{level: 3, id: 'USACE', name: 'USACE', shortname: '' }
		]},
		{ level: 2, id: '1700', name: 'DEPT OF THE NAVY', shortname: '', children: [
			{ level: 3, id: 'MSC', name: 'MSC', shortname: '' },
			{ level: 3, id: 'NAVAIR', name: 'NAVAIR', shortname: '' },
			{ level: 3, id: 'NAVFAC', name: 'NAVFAC', shortname: '' },
			{ level: 3, id: 'NAVSEA', name: 'NAVSEA', shortname: '' },			
			{ level: 3, id: 'NAVSUP', name: 'NAVSUP', shortname: '', children: [
				{ level: 4, id: 'NAVSUP GLS', name: '', shortname: '', children: [
					{ level: 5, id: 'NAVSUP FLC BAHRAIN', name: 'NAVSUP FLC BAHRAIN', shortname: '' },
					{ level: 5, id: 'NAVSUP FLC JAX', name: 'NAVSUP FLC JACKSONVILLE', shortname: '' },
					{ level: 5, id: 'NAVSUP FLC NORFOLK', name: 'NAVSUP FLC NORFOLK', shortname: '' },
					{ level: 5, id: 'NAVSUP FLC PEARL', name: 'NAVSUP FLC PEARL HARBOR', shortname: '' },
					{ level: 5, id: 'NAVSUP FLC PUGET', name: 'NAVSUP FLC PUGET SOUND', shortname: '' },
					{ level: 5, id: 'NAVSUP FLC SAN DIEGO', name: 'NAVSUP FLC SAN DIEGO', shortname: '' },
					{ level: 5, id: 'NAVSUP FLC SIGONELLA', name: 'NAVSUP FLC SIGONELLA', shortname: '', children: [
						{ level: 6, id: 'NAVSUP FLC SIG BAHRN', name: 'NAVSUP FLC SIGONELLA BAHRAIN OFFICE', shortname: '' },
						{ level: 6, id: 'NAVSUP FLC SIG NAPLE', name: 'FLC SIGONELLA NAPLES OFFICE', shortname: '' }
					] },
					{ level: 5, id: 'NAVSUP FLC YOKOSUKA', name: 'NAVSUP FLC YOKOSUKA', shortname: '' },
					{ level: 5, id: 'NASUP FLC YOKOSUKA', name: 'NAVSUP FLC YOKOSUKA', shortname: '' },
					{ level: 5, id: 'NAVSUP FLC SINGAPORE', name: 'NAVSUP FLC SINGAPORE', shortname: '' },
					{ level: 5, id: 'NAVSUP FLC YOKO SASB', name: 'NAVSUP FLC YOKOSUKA SASEBO OFFICE', shortname: '' }
				]},				
				{ level: 4, id: 'NAVSUP OTHER HCA', name: 'NAVSUP OTHER HCA', shortname: '', children: [
					{ level: 5, id: 'BUMED', name: 'BUMED', shortname: '', children: [
						{ level: 6, id: 'NAVY MEDICINE CMD', name: 'NAVY MEDICINE SUPPORT COMMAND', shortname: '', children: [
							{ level: 7, id: 'N62645', name: 'NAVAL MEDICAL LOGISTICS COMMAND', shortname: '' },
							{ level: 7, id: 'N68853', name: 'NAVY DRUG SCREENING LABORATORY', shortname: '' },
							{ level: 7, id: 'N0622A', name: 'NAVY MEDICINE PROFESSIONAL', shortname: '' }
						] },
						{ level: 6, id: 'NAVY MEDICINE EAST', name: 'NAVY MEDICINE EAST', shortname: '', children: [
							{ level: 7, id: 'N61726', name: 'NAVAL BRANCH HEALTH CLINIC GROTON', shortname: '' },
							{ level: 7, id: 'N00232', name: 'NAVAL HOSPITAL JACKSONVILLE FL', shortname: '' },
							{ level: 7, id: 'N00203', name: 'NAVAL MEDICAL CENTER PORTSMOUTH VA', shortname: '' },
							{ level: 7, id: 'N00183', name: 'NAVAL HEALTH CLINIC CHARLESTON', shortname: '' },
							{ level: 7, id: 'N68084', name: 'NAVY-MARINE CORPS PUBLIC HEALTH CTR', shortname: '' },
							{ level: 7, id: 'N66098', name: 'NAVAL HEALTH CLINIC', shortname: '' },
							{ level: 7, id: 'N00105', name: 'NAVAL BRANCH HEALTH CLINIC', shortname: '' },
							{ level: 7, id: 'N00231', name: 'NAVAL HEALTH CLINIC', shortname: '' },
							{ level: 7, id: 'N39163', name: 'NAVAL HOSPITAL SIGONELLA ITALY', shortname: '' },
							{ level: 7, id: 'N00162', name: 'NAVAL HEALTH CLINIC ANNAPOLIS MD', shortname: '' },
							{ level: 7, id: 'N68850', name: 'NAVAL DRUG SCREENING LABORATORY', shortname: '' }
						] },
						{ level: 6, id: 'NAVY MEDICINE NCA', name: 'NAVY MEDICINE NATIONAL CAPITAL AREA', shortname: '', children: [
							{ level: 7, id: 'N00168', name: 'WALTER REED NATIONAL', shortname: '' }
						] },
						{ level: 6, id: 'NAVY MEDICINE WEST', name: 'NAVY MEDICINE WEST', shortname: '', children: [
							{ level: 7, id: 'N39467', name: 'NAVAL MEDICAL RESEARCH UNIT', shortname: '' },
							{ level: 7, id: 'N41817', name: 'NAVAL MEDICIAL RESEARCH UNIT DAYTON', shortname: '' },
							{ level: 7, id: 'N66097', name: 'NHLTHCLINIC OAK HARBOR WA', shortname: '' },
							{ level: 7, id: 'N00259', name: 'NAVAL MEDICAL CENTER SAN DIEGO CA', shortname: '' },
							{ level: 7, id: 'N68095', name: 'NAVAL HOSPITAL', shortname: '' },
							{ level: 7, id: 'N68096', name: 'U S NAVAL HOSPITAL GUAM', shortname: '' },
							{ level: 7, id: 'N35949', name: 'NAVAL HOSPITAL TWENTYNINE PALMS CA', shortname: '' },
							{ level: 7, id: 'N68094', name: 'NAVAL HOSPITAL CAMP PENDLETON', shortname: '' },
							{ level: 7, id: 'N62814', name: 'NAVAL MED RESEARCH CENTER ASIA', shortname: '' }
						] }
					] },					
					{ level: 5, id: 'BUPERS', name: 'BUPERS', shortname: '', children: [
						{ level: 7, id: 'N62447', name: 'NTAG PITTSBURGH', shortname: '' },
						{ level: 7, id: 'N68401', name: 'NAVY RECRUITING DISTRICT SAN DIEGO', shortname: '' },
						{ level: 7, id: 'N62980', name: 'NAVY PERSONNEL COMMAND', shortname: '' },
						{ level: 7, id: 'N45610', name: 'NAVAL CONSOLIDATED BRIG CHARLESTON', shortname: '' },
						{ level: 7, id: 'N38305', name: 'NAVCONBRIG CHESAPEAKE', shortname: '' },
						{ level: 7, id: 'N62410', name: 'NAVY RECRUITING DISTRICT PHOENIX', shortname: '' },
						{ level: 7, id: 'N62446', name: 'NAVY RECRUITING DIST PHILADELPHIA', shortname: '' },
						{ level: 7, id: 'N63292', name: 'NROTCU YALE UNIVERSITY', shortname: '' },
						{ level: 7, id: 'N60268', name: 'NAVY RECRUITING DISTRICT CHICAGO', shortname: '' },
						{ level: 7, id: 'N35391', name: 'FLEET BAND ACTIVITIES', shortname: '' },
						{ level: 7, id: 'N62435', name: 'NAVY RECRUITING DIST NEW ENGLAND', shortname: '' },
						{ level: 7, id: 'N62430', name: 'NAVY RECRUITING DISTRICT RALEIGH', shortname: '' },
						{ level: 7, id: 'N62431', name: 'NAVY RECRUITING DISTRICT RICHMOND', shortname: '' },
						{ level: 7, id: 'N69223', name: 'OCHR PHILADELPHIA OPS CENTER', shortname: '' },
						{ level: 7, id: 'N69199', name: 'OCHR NORFOLK OPERATIONS CENTER', shortname: '' },
						{ level: 7, id: 'N00022', name: 'CHIEF OF NAVAL PERSONNEL', shortname: '' },
						{ level: 7, id: 'N62425', name: 'NTAG NASHVILLE', shortname: '' },
						{ level: 7, id: 'N68323', name: 'COMMANDER NAVAL LEGAL SERV COMMAND', shortname: '' },
						{ level: 7, id: 'N62412', name: 'NRPS MONTGOMERY', shortname: '' },
						{ level: 7, id: 'N62416', name: 'NAVY TALENT ACQ GROUP', shortname: '' },
						{ level: 7, id: 'N62429', name: 'NAVY TALENT ACQUISITION GROUP', shortname: '' },
						{ level: 7, id: 'N62437', name: 'NAVY RECRUITING DISTRICT DALLAS', shortname: '' },
						{ level: 7, id: 'N66972', name: 'NAVY RECRUITING DISTRICT MIAMI', shortname: '' },
						{ level: 7, id: 'N67596', name: 'NAVY RECRUITING DIST SAN ANTONIO', shortname: '' },
						{ level: 7, id: 'N68011', name: 'NAVY RECRUITING DISTRICT ST LOUIS', shortname: '' },
						{ level: 7, id: 'N62439', name: 'NAVY RECRUITING DISTRICT MICHIGAN', shortname: '' }
					] },
					{ level: 5, id: 'CNET', name: 'CNET', shortname: '', children: [
						{ level: 7, id: 'N63215', name: 'NROTCU ILLINOIS INST OF TECHNOLOGY', shortname: '' },
						{ level: 7, id: 'N63218', name: 'NROTCU CHICAGO AREA', shortname: '' },
						{ level: 7, id: 'N63222', name: 'NROTCU UNIVERSITY OF KANSAS', shortname: '' },
						{ level: 7, id: 'N63225', name: 'NROTCU MARQUETTE UNIV', shortname: '' },
						{ level: 7, id: 'N63226', name: 'NROTCU UNIV OF MINNESOTA', shortname: '' },
						{ level: 7, id: 'N63229', name: 'NROTCU UNIV OF OKLAHOMA', shortname: '' },
						{ level: 7, id: 'N63294', name: 'NROTCU UNIVERSITY OF ROCHESTER', shortname: '' },
						{ level: 7, id: 'N63308', name: 'NROTC UNIV NORTH CAROLINA', shortname: '' },
						{ level: 7, id: 'N63311', name: 'NROTCU PHILADELPHIA PA', shortname: '' },
						{ level: 7, id: 'N64181', name: 'DEPARTMENT OF NAVAL SCIENCE', shortname: '' },
						{ level: 7, id: 'N64272', name: 'DEPT OF NAVAL SCIENCE', shortname: '' },
						{ level: 7, id: 'N68699', name: 'NAVY ROTCU HAMPTON ROADS', shortname: '' },
						{ level: 7, id: 'N68877', name: 'NROTCU CARNEGIE MELLON UNIVERSITY', shortname: '' },
						{ level: 7, id: 'N35026', name: 'CENEODDIVE LEARNING SITE GLKS', shortname: '' },
						{ level: 7, id: 'N63214', name: 'NROTCU UNIVERSITY OF COLORADO', shortname: '' },
						{ level: 7, id: 'N66074', name: 'NROTCU PRAIRIE VIEW A AND M UNIV', shortname: '' },						
						{ level: 7, id: 'N3597A', name: 'SUBMARINE LEARNING CENTER', shortname: '' },
						{ level: 7, id: 'N68710', name: 'NROTCU VIRGINIA POLYTECHNIC', shortname: '' },
						{ level: 7, id: 'N63209', name: 'NROTCU UNIV OF NEW MEXICO', shortname: '' },
						{ level: 7, id: 'N63309', name: 'NROTCU OHIO STATE UNIVERSITY', shortname: '' },
						{ level: 7, id: 'N63310', name: 'NROTCU PENNSYLVANIA STATE UNIV', shortname: '' },
						{ level: 7, id: 'N0612A', name: 'NAVAL CONSTRUCTION TRAINING CENTER', shortname: '' },
						{ level: 7, id: 'N3593A', name: 'CENTER FOR SEAL SWCC', shortname: '' },
						{ level: 7, id: 'N3761A', name: 'CENTER FOR SECURITY FORCES', shortname: '' },
						{ level: 7, id: 'N63224', name: 'NROTCU UNIV OF WISCONSIN', shortname: '' },
						{ level: 7, id: 'N68355', name: 'NROTCU VIRGINIA MILITARY INSTITUTE', shortname: '' },
						{ level: 7, id: 'N50045', name: 'NROTCU ARIZONA STATE UNIVERSITY', shortname: '' },
						{ level: 7, id: 'N61690', name: 'TRAINING SUPPORT CENTER', shortname: '' },
						{ level: 7, id: 'N63303', name: 'COMMANDING OFFICER', shortname: '' },
						{ level: 7, id: 'N63295', name: 'NROTCU RENSSELAER POLYTECHNIC INST', shortname: '' },
						{ level: 7, id: 'N63313', name: 'NROTCU UNIV OF SOUTH CAROLINA', shortname: '' },
						{ level: 7, id: 'N63234', name: 'NROTCU UNIVERSITY OF ILLINOIS', shortname: '' },
						{ level: 7, id: 'N68717', name: 'NROTCU BOSTON CONSORTIUM', shortname: '' },
						{ level: 7, id: 'N63317', name: 'NROTCU UNIVERSITY OF VIRGINIA', shortname: '' },
						{ level: 7, id: 'N63217', name: 'NROTCU OREGON STATE UNIV', shortname: '' },
						{ level: 7, id: 'N63211', name: 'NROTCU MICHIGAN UNIVERSITY', shortname: '' },
						{ level: 7, id: 'N63216', name: 'NROTCU UNIV OF MISSOURI', shortname: '' },
						{ level: 7, id: 'N63219', name: 'NROTCU HOUSTON CONSORTIUM', shortname: '' },
						{ level: 7, id: 'N00076', name: 'NAVAL EDUCATION AND TRAINING', shortname: '' },
						{ level: 7, id: 'N63231', name: 'NROTCU UNIVERSITY OF UTAH', shortname: '' },
						{ level: 7, id: 'N63306', name: 'NROTCU MIAMI UNIV', shortname: '' },
						{ level: 7, id: 'N3596A', name: 'CENTER FOR SURFACE COMBAT SYSTEMS', shortname: '' },
						{ level: 7, id: 'N63210', name: 'NROTCU IOWA STATE UNIV', shortname: '' },
						{ level: 7, id: 'N63212', name: 'THE UNIVERSITY OF TEXAS AT AUSTIN', shortname: '' },
						{ level: 7, id: 'N63221', name: 'NROTCU UNIV OF SOUTHERN CALIFORNIA', shortname: '' },
						{ level: 7, id: 'N63223', name: 'NROTCU UNIV OF NEBRASKA', shortname: '' },
						{ level: 7, id: 'N63227', name: 'NROTC UNIT UNIVERSITY OF IDAHO', shortname: '' },
						{ level: 7, id: 'N63228', name: 'NROTC UNIT TULANE UNIVERSITY', shortname: '' },
						{ level: 7, id: 'N63230', name: 'NROTCU UNIV OF NOTRE DAME', shortname: '' },
						{ level: 7, id: 'N63307', name: 'NROTCU UNIV OF MISSISSIPPI', shortname: '' },
						{ level: 7, id: 'N63315', name: 'NAVAL ROTC VANDERBILT UNIVERSITY', shortname: '' },
						{ level: 7, id: 'N66612', name: 'NROTCU THE CITADEL', shortname: '' },
						{ level: 7, id: 'N66753', name: 'NROTCU JACKSONVILLE UNIVERSITY', shortname: '' },
						{ level: 7, id: 'N66809', name: 'NROTCU SAVANNAH STATE COLLEGE', shortname: '' },
						{ level: 7, id: 'N68064', name: 'NROTCU UNIVERSITY OF FLORIDA', shortname: '' },
						{ level: 7, id: 'N68072', name: 'NROTCU TEXAS A AND M UNIV', shortname: '' },
						{ level: 7, id: 'N68692', name: 'NROTCU UNIVERSITY OF SAN DIEGO', shortname: '' },
						{ level: 7, id: 'N68726', name: 'NROTCU GEORGE WASHINGTON UNIVERSITY', shortname: '' },
						{ level: 7, id: 'N63291', name: 'NROTCU CORNELL UNIVERSITY', shortname: '' },
						{ level: 7, id: 'N63299', name: 'NROTCU NC PIEDMONT DUKE UNIV', shortname: '' },
						{ level: 7, id: 'N68141', name: 'NROTCU MAINE MARITIME ACADEMY', shortname: '' },
						{ level: 7, id: 'N3426B', name: 'NROTCU UNIVERSITY OF SOUTH FLORIDA', shortname: '' },
						{ level: 7, id: 'N3582A', name: 'NROTCU EMBRY RIDDLE AERONAUTICAL UN', shortname: '' },
						{ level: 7, id: 'N63213', name: 'NROTCU UC BERKELEY', shortname: '' },
						{ level: 7, id: 'N68322', name: 'NAVAL EDUCATION AND TRAINING', shortname: '' },
						{ level: 7, id: 'N63220', name: 'NROTCU UNIV OF CALIFORNIA', shortname: '' },
						{ level: 7, id: 'N63296', name: 'NROTCU AUBURN UNIVERSTIY', shortname: '' }
					] },
					{ level: 5, id: 'CNIC', name: 'CNIC', shortname: '' },
					{ level: 5, id: 'COMUSNAVEUR', name: 'COMUSNAVEUR', shortname: '' },
					{ level: 5, id: 'EUROPE', name: 'EUROPE', shortname: '' },
					{ level: 5, id: 'MISC', name: 'MISC', shortname: '' },
					{ level: 5, id: 'NAVFACSYSCOM', name: 'NAVFACSYSCOM', shortname: '' },
					{ level: 5, id: 'NAVRESFOR', name: 'NAVRESFOR', shortname: '' },
					{ level: 5, id: 'NIOC', name: 'NIOC', shortname: '' },
					{ level: 5, id: 'NRCC', name: 'NRCC', shortname: '' },
					{ level: 5, id: 'SPAWARSYSCOM', name: 'SPAWARSYSCOM', shortname: '' },
					{ level: 5, id: 'US FLEET CYBER CMD', name: 'US FLEET CYBER CMD', shortname: '' },
					{ level: 5, id: 'US FLEET FORCES CMD', name: 'US FLEET FORCES CMD', shortname: '' },
					{ level: 5, id: 'US NAVY FLEET', name: 'US NAVY FLEET', shortname: '' },
					{ level: 5, id: 'US PACIFIC FLEET', name: 'US PACIFIC FLEET', shortname: '', children: [
						{ level: 7, id: 'N40628', name: 'NMCPAC CONUS WEST DIVISION', shortname: '' },
						{ level: 7, id: 'N09995', name: 'ELECTRONIC ATTACK SQUADRON VAQ 129', shortname: '' },
						{ level: 7, id: 'R09995', name: 'ELECTRONIC ATTACK SQUADRON VAQ 129', shortname: '' },
						{ level: 7, id: 'R09459', name: 'VAW 113 ATTENDING CTPL', shortname: '' },
						{ level: 7, id: 'R55611', name: 'NAVAL CONSTRUCTION REGIMENT', shortname: '' },
						{ level: 7, id: 'V09526', name: 'VAW-124', shortname: '' },
						{ level: 7, id: 'V09963', name: 'COMMANDING OFFICER', shortname: '' },
						{ level: 7, id: 'N62758', name: 'SRF AND JRMC YOKOSUKA', shortname: '' },
						{ level: 7, id: 'R09607', name: 'FLEET LOGISTICS SUPPORT SQ 30 VRC30', shortname: '' },
						{ level: 7, id: 'R55752', name: 'NAVAL CONSTRUCTION GROUP ONE', shortname: '' },
						{ level: 7, id: 'V09052', name: 'AIRBORNE COMMAND AND CONTROL', shortname: '' },
						{ level: 7, id: 'R68951', name: 'DIRECTOR SUBMARINE FORCE US', shortname: '' },
						{ level: 7, id: 'R44429', name: 'NAVAL SUBMARINE SUPPORT COMMAND', shortname: '' },
						{ level: 7, id: 'N62853', name: 'UNDERSEA SURVEILLANCE', shortname: '' },
						{ level: 7, id: 'N62854', name: 'NAVOCEANPROFAC WHIDBEY ISLAND WA', shortname: '' },
						{ level: 7, id: 'N62855', name: 'NAVOCEANPROFAC DAM NECK VA', shortname: '' },
						{ level: 7, id: 'N55575', name: 'STRATEGIC COMMUNICATIONS WING 1', shortname: '' },
						{ level: 7, id: 'N68951', name: 'DIRECTOR SUBMARINE FORCE US', shortname: '' },
						{ level: 7, id: 'N63407', name: 'NAWDC', shortname: '' },
						{ level: 7, id: 'N57020', name: 'COMMANDER SUBMARINE FORCE', shortname: '' },
						{ level: 7, id: 'R57020', name: 'COMMANDER SUBMARINE FORCE', shortname: '' },
						{ level: 7, id: 'N09963', name: 'COMMANDING OFFICER', shortname: '' },
						{ level: 7, id: 'N09526', name: 'VAW-124', shortname: '' },
						{ level: 7, id: 'N09922', name: 'VAW-125', shortname: '' },
						{ level: 7, id: 'N55630', name: 'HELICOPTER ANTISUBMARINE LIGHT WING', shortname: '' },
						{ level: 7, id: 'N64100', name: 'SRF AND JRMC YOKOSUKA', shortname: '' },
						{ level: 7, id: 'N57046', name: 'NECC PACIFIC', shortname: '' },
						{ level: 7, id: 'N09520', name: 'STRIKE FIGHTER WING US PAC FLEET', shortname: '' },
						{ level: 7, id: 'N55627', name: 'ELECTRONIC ATTACK WING US PACIFIC', shortname: '' },
						{ level: 7, id: 'R55635', name: 'HELICOPTER SEA COMBAT WING PACIFIC', shortname: '' }
					] },
					{ level: 7, id: 'N46804', name: 'OFFICE OF NAVAL INTELLIGENCE', shortname: '' },
					{ level: 7, id: 'N00250', name: 'NAVY EXCHANGE SERVICE COMMAND', shortname: '' }
				] },
				{ level: 4, id: 'NAVSUP WSS', name: 'NAVSUP WEAPON SYSTEMS SUPPORT', shortname: '', children: [
					{ level: 5, id: 'NAVSUP WSS MECH', name: 'NAVSUP WSS MECHANICSBURG', shortname: '', children: [
						{ level: 7, id: 'N00104', name: 'NAVSUP WEAPON SYSTEMS SUPPORT MECH', shortname: '' }
					] },
					{ level: 5, id: 'NAVSUP WSS PHIL', name: 'NAVSUP WSS PHILADELPHIA', shortname: '', children: [
						{ level: 7, id: 'N00383', name: 'NAVSUP WEAPON SYSTEMS SUPPORT', shortname: '' }
					] }
				] }
			] },
			{ level: 3, id: 'ONR', name: 'ONR', shortname: '' },
			{ level: 3, id: 'SPAWAR', name: 'SPAWAR', shortname: '' },
			{ level: 3, id: 'SSP', name: 'SSP', shortname: '' },
			{ level: 3, id: 'USMC', name: 'USMC', shortname: '' }
		]},
		{ level: 2, id: '97AD', name: 'IMMEDIATE OFFICE OF THE SECRETARY OF DEFENSE', shortname: ''},
		{ level: 2, id: '97EX', name: 'INSPECTOR GENERAL, OFFICE OF', shortname: ''},
		{ level: 2, id: '97BJ', name: 'JOINT CHIEFS OF STAFF, ORGANIZATION OF', shortname: ''},
		{ level: 2, id: '97F7', name: 'JOINT IMPROVISED EXPLOSIVE DEVICE DEFEAT ORGANIZATION', shortname: 'JIEDDO'},
		{ level: 2, id: '97JC', name: 'MISSILE DEFENSE AGENCY', shortname: 'MDA'},
		{ level: 2, id: '97AB', name: 'NATIONAL GEOSPATIAL-INTELLIGENCE AGENCY (NGA)', shortname: ''},
		{ level: 2, id: '97CG', name: 'NATIONAL SECURITY AGENCY/CENTRAL SECURITY SERVICE', shortname: ''},
		{ level: 2, id: '97F6', name: 'OFFICE OF ECONOMIC ADJUSTMENT', shortname: ''},
		{ level: 2, id: '9765', name: 'PENTAGON FORCE PROTECTION AGENCY', shortname: ''},
		{ level: 2, id: '97SD', name: 'SPACE DEVELOPMENT AGENCY', shortname: ''},
		{ level: 2, id: '97HW', name: 'UNIFORMED SERVICES UNIVERSITY OF THE HEALTH SCIENCES', shortname: ''},
		{ level: 2, id: '96CE', name: 'U.S. ARMY CORPS OF ENGINEERS - CIVIL PROGRAM FINANCING ONLY', shortname: ''},
		{ level: 2, id: '97CY', name: 'U.S. CYBER COMMAND', shortname: ''},
		{ level: 2, id: '97ZS', name: 'U.S. SPECIAL OPERATIONS COMMAND', shortname: 'USSOCOM'},
		{ level: 2, id: '9776', name: 'USTRANSCOM', shortname: ''},
		{ level: 2, id: '97F5', name: 'WASHINGTON HEADQUARTERS SERVICES', shortname: 'WHS'}
	]},
	{ level: 1, id: '7611', name: 'DWIGHT DAVID EISENHOWER CENTENNIAL COMMISSION'},
	{ level: 1, id: '0905', name: 'DWIGHT D. EISENHOWER MEMORIAL COMMISSION'},
	{ level: 1, id: '9100', name: 'EDUCATION, DEPARTMENT OF'},
	{ level: 1, id: '9523', name: 'ELECTION ASSISTANCE COMMISSION'},
	{ level: 1, id: '8900', name: 'ENERGY, DEPARTMENT OF'},
	{ level: 1, id: '6800', name: 'ENVIRONMENTAL PROTECTION AGENCY'},
	{ level: 1, id: '4500', name: 'EQUAL EMPLOYMENT OPPORTUNITY COMMISSION'},
	{ level: 1, id: '1100', name: 'EXECUTIVE OFFICE OF THE PRESIDENT'},
	{ level: 1, id: '8300', name: 'EXPORT-IMPORT BANK OF THE U.S.'},
	{ level: 1, id: '7800', name: 'FARM CREDIT ADMINISTRATION'},
	{ level: 1, id: '2700', name: 'FEDERAL COMMUNICATIONS COMMISSION'},
	{ level: 1, id: '5100', name: 'FEDERAL DEPOSIT INSURANCE CORPORATION'},
	{ level: 1, id: '9506', name: 'FEDERAL ELECTION COMMISSION'},
	{ level: 1, id: '5800', name: 'FEDERAL EMERGENCY MANAGEMENT AGENCY'},
	{ level: 1, id: '9562', name: 'FEDERAL FINANCIAL INSTITUTIONS EXAMINATION COUNCIL'},
	{ level: 1, id: '8200', name: 'FEDERAL HOME LOAN BANK BOARD'},
	{ level: 1, id: '9542', name: 'FEDERAL HOUSING FINANCE AGENCY'},
	{ level: 1, id: '9540', name: 'FEDERAL HOUSING FINANCE BOARD'},
	{ level: 1, id: '1028', name: 'FEDERAL JUDICIAL CENTER'},
	{ level: 1, id: '5400', name: 'FEDERAL LABOR RELATIONS AUTHORITY'},
	{ level: 1, id: '6500', name: 'FEDERAL MARITIME COMMISSION'},
	{ level: 1, id: '9300', name: 'FEDERAL MEDIATION AND CONCILIATION SERVICE'},
	{ level: 1, id: '9504', name: 'FEDERAL MINE SAFETY AND HEALTH REVIEW COMMISSION'},
	{ level: 1, id: '1023', name: 'FEDERAL PUBLIC DEFENDERS'},
	{ level: 1, id: '9559', name: 'FEDERAL RESERVE SYSTEM, BOARD OF GOVERNORS'},
	{ level: 1, id: '2600', name: 'FEDERAL RETIREMENT THRIFT INVESTMENT BOARD'},
	{ level: 1, id: '2900', name: 'FEDERAL TRADE COMMISSION'},
	{ level: 1, id: '9585', name: 'FINANCING CORPORATION (FICO)'},
	{ level: 1, id: '4700', name: 'GENERAL SERVICES ADMINISTRATION'},
	{ level: 1, id: '0500', name: 'GOVERNMENT ACCOUNTABILITY OFFICE'},
	{ level: 1, id: '0400', name: 'GOVERNMENT PRINTING OFFICE'},
	{ level: 1, id: '9533', name: 'GULF COAST ECOSYSTEM RESTORATION COUNCIL'},
	{ level: 1, id: '9510', name: 'HARRY S TRUMAN SCHOLARSHIP FOUNDATION'},
	{ level: 1, id: '7500', name: 'HEALTH AND HUMAN SERVICES, DEPARTMENT OF'},
	{ level: 1, id: '7000', name: 'HOMELAND SECURITY, DEPARTMENT OF'},
	{ level: 1, id: '0050', name: 'HOUSE OF REPRESENTATIVES, THE'},
	{ level: 1, id: '8600', name: 'HOUSING AND URBAN DEVELOPMENT, DEPARTMENT OF'},
	{ level: 1, id: '4811', name: 'INDIAN LAW AND ORDER COMMISSION'},
	{ level: 1, id: '9535', name: 'INSTITUTE OF AMERICAN INDIAN AND ALASKA NATIVE CULTURE AND ARTS DEVELOPMENT'},
	{ level: 1, id: '9519', name: 'INTELLIGENCE COMMUNITY STAFF'},
	{ level: 1, id: '4854', name: 'INTER-AGENCY COUNCIL FOR HOMELESS'},
	{ level: 1, id: '4865', name: 'INTERAGENCY COUNCIL ON THE HOMELESS'},
	{ level: 1, id: '9554', name: 'INTERAGENCY COUNCIL ON THE HOMELESS'},
	{ level: 1, id: '1400', name: 'INTERIOR, DEPARTMENT OF THE'},
	{ level: 1, id: '49SA', name: 'INTERNATIONAL ASTRONOMICAL UNION'},
	{ level: 1, id: '19BM', name: 'INTERNATIONAL BOUNDARY AND WATER COMMISSION: U.S.-MEXICO'},
	{ level: 1, id: '49SU', name: 'INTERNATIONAL COUNCIL OF SCIENTIFIC UNIONS'},
	{ level: 1, id: '4821', name: 'INTERNATIONAL CULTURAL AND TRADE CENTER COMMISSION'},
	{ level: 1, id: '49SG', name: 'INTERNATIONAL GEOGRAPHICAL UNION'},
	{ level: 1, id: '49SM', name: 'INTERNATIONAL MATHEMATICAL UNION'},
	{ level: 1, id: '3400', name: 'INTERNATIONAL TRADE COMMISSION'},
	{ level: 1, id: '49SV', name: 'INTERNATIONAL UNION FOR PURE AND APPLIED BIOPHYSICS'},
	{ level: 1, id: '49SK', name: 'INTERNATIONAL UNION OF BIOCHEMISTRY'},
	{ level: 1, id: '49SB', name: 'INTERNATIONAL UNION OF BIOLOGICAL SCIENCES'},
	{ level: 1, id: '49SX', name: 'INTERNATIONAL UNION OF CRYSTALLOGRAPHY'},
	{ level: 1, id: '49SD', name: 'INTERNATIONAL UNION OF GEODESY AND GEOPHYSICS'},
	{ level: 1, id: '49SE', name: 'INTERNATIONAL UNION OF GEOLOGICAL SCIENCES'},
	{ level: 1, id: '49SY', name: 'INTERNATIONAL UNION OF IMMUNOLOGICAL SOCIETIES'},
	{ level: 1, id: '49SW', name: 'INTERNATIONAL UNION OF MICROBOLOGICAL SOCIETIES'},
	{ level: 1, id: '49SN', name: 'INTERNATIONAL UNION OF NUTRITIONAL SCIENCES'},
	{ level: 1, id: '49SL', name: 'INTERNATIONAL UNION OF PHARMACOLOGY'},
	{ level: 1, id: '49SP', name: 'INTERNATIONAL UNION OF PHYSIOLOGICAL SCIENCES'},
	{ level: 1, id: '49SS', name: 'INTERNATIONAL UNION OF PSYCHOLOGICAL SCIENCE'},
	{ level: 1, id: '49SC', name: 'INTERNATIONAL UNION OF PURE AND APPLIED CHEMISTRY'},
	{ level: 1, id: '49SF', name: 'INTERNATIONAL UNION OF PURE AND APPLIED PHYSICS'},
	{ level: 1, id: '49SR', name: 'INTERNATIONAL UNION OF RADIO SCIENCE'},
	{ level: 1, id: '49SH', name: 'INTERNATIONAL UNION OF THE HISTORY AND PHILOSOPHY OF SCIENCE'},
	{ level: 1, id: '49ST', name: 'INTERNATIONAL UNION OF THEORETICAL AND APPLIED MECHANICS'},
	{ level: 1, id: '3000', name: 'INTERSTATE COMMERCE COMMISSION'},
	{ level: 1, id: '4607', name: 'INTERSTATE COMMISSION ON THE POTOMAC RIVER BASIN'},
	{ level: 1, id: '9541', name: 'JAMES MADISON MEMORIAL FELLOWSHIP COMMISSION'},
	{ level: 1, id: '9512', name: 'JAPAN-U.S. FRIENDSHIP COMMISSION'},
	{ level: 1, id: '3352', name: 'J. F. KENNEDY CENTER FOR THE PERFORMING ARTS'},
	{ level: 1, id: '0914', name: 'JOHN C. STENNIS CENTER FOR PUBLIC DEVELOPMENT'},
	{ level: 1, id: '1018', name: 'JUDICIAL PANEL ON MULTIDISTRICT LITIGATION'},
	{ level: 1, id: '1500', name: 'JUSTICE, DEPARTMENT OF'},
	{ level: 1, id: '1600', name: 'LABOR, DEPARTMENT OF'},
	{ level: 1, id: '0300', name: 'LIBRARY OF CONGRESS'},
	{ level: 1, id: '9513', name: 'MARINE MAMMAL COMMISSION'},
	{ level: 1, id: '7615', name: 'MARTIN LUTHER KING, JR. FEDERAL HOLIDAY COMMISSION'},
	{ level: 1, id: '4835', name: 'MEDICARE PAYMENT ADVISORY COMMISSION'},
	{ level: 1, id: '4100', name: 'MERIT SYSTEMS PROTECTION BOARD'},
	{ level: 1, id: '9543', name: 'MILLENIUM CHALLENGE CORPORATION'},
	{ level: 1, id: '9668', name: 'MISSISSIPPI RIVER COMMISSION'},
	{ level: 1, id: '9545', name: 'MORRIS K. UDALL SCHOLARSHIP AND EXCELLENCE IN NATIONAL ENVIRONMENTAL POLICY FOUNDATION'},
	{ level: 1, id: '8000', name: 'NATIONAL AERONAUTICS AND SPACE ADMINISTRATION'},
	{ level: 1, id: '8800', name: 'NATIONAL ARCHIVES AND RECORDS ADMINISTRATION'},
	{ level: 1, id: '4808', name: 'NATIONAL BIPARTISAN COMMISSION ON THE FUTURE OF MEDICARE'},
	{ level: 1, id: '9502', name: 'NATIONAL CAPITAL PLANNING COMMISSION'},
	{ level: 1, id: '0913', name: 'NATIONAL COMMISSION ON ACQUIRED IMMUNE DEFICIENCY SYNDROME'},
	{ level: 1, id: '9527', name: 'NATIONAL COMMISSION ON LIBRARIES AND INFORMATION SCIENCE'},
	{ level: 1, id: '9584', name: 'NATIONAL COMMISSION ON SEVERELY DISTRESS PUBLIC HOUSING'},
	{ level: 1, id: '0916', name: 'NATIONAL COMMISSION ON TERRORISM'},
	{ level: 1, id: '0973', name: 'NATIONAL COMMISSION ON TERRORIST ATTACKS UPON THE UNITED STATES'},
	{ level: 1, id: '4852', name: 'NATIONAL COMMISSION TO PREVENT INFANT MORTALITY'},
	{ level: 1, id: '9583', name: 'NATIONAL COMM ON AMERICAN INDIAN, ALASKA NATIVE, NATIVE HAWAIIAN HOUSING'},
	{ level: 1, id: '955P', name: 'NATIONAL COMMUNICATIONS SYSTEM'},
	{ level: 1, id: '9555', name: 'NATIONAL COMMUNICATIONS SYSTEM'},
	{ level: 1, id: '9509', name: 'NATIONAL COUNCIL ON DISABILITY'},
	{ level: 1, id: '9525', name: 'NATIONAL COUNTERINTELLIGENCE CENTER', shortname: 'NCIC'},
	{ level: 1, id: '2500', name: 'NATIONAL CREDIT UNION ADMINISTRATION'},
	{ level: 1, id: '5920', name: 'NATIONAL ENDOWMENT FOR THE ARTS', shortname: 'NEA'}
  ]
};